
version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
  - name: Reputation
    description: "A starter dbt model"
    columns:
        - name: id
          description: "The primary key for this table"
          tests:
            - unique
            - not_null
    - name: QUESTIONS
      description: "A starter dbt model"
      columns:
        - name: id
          description: "The primary key for this table"
          tests:
            - unique
            - not_null
     - name: QUESTIONS_LIKE
       description: "A starter dbt model"
       columns:
         - name: id
           description: "The primary key for this table"
           tests:
             - unique
             - not_null
      - name: QUESTIONS_COUNT
        description: "A starter dbt model"
        columns:
          - name: id
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
      - name: MOST_POPULAR_BADGES
        description: "A starter dbt model"
        columns:
          - name: id
            description: "The primary key for this table"
            tests:
              - unique
              - not_null
